{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
  labels:
    simpletrip: {{ include "common.name" . }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.servicePort }}
  selector:
    simpletrip: {{ include "common.name" . }}
{{- end -}}
