exports:
  data:
    # DEPLOYMENT
    imageRepository: 432560034976.dkr.ecr.eu-central-1.amazonaws.com/simpletrip
    imagePullPolicy: Always
    imageTag: latest

    portsContainerPort: 8080

    livenessProbeInitialDelaySeconds: 300
    readinessProbeInitialDelaySeconds: 30

    secretsEnabled: false
    secretsName: default

    awsEnabled: false
    awsSecretKeyRefName: default

    mockClientsConfEnabled: false

    # SERVICE
    serviceType: NodePort
    servicePort: 8080

    # HorizontalPodAutoscaler
    hpaTargetCPUUtilizationPercentage: 80
    hpaMinReplicas: 2
    hpaMaxReplicas: 10

