name: Deploy Workflow
run-name: ${{ github.actor }} has triggered a Deploy Workflow! 🚀

on:
  push:
    branches: [main]

jobs:
  package-and-publish:
    name: Package & Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run linter
        run: helm lint charts/yilu-common --set image.tag="test" --set serviceName="ci-test"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PAGES_INDEX_PATH: docs
        with:
          pages_branch: yilu-common
          skip_existing: true
          packages_with_index: true

      - name: Copy readme
        run: |
          git checkout yilu-common
          git show main:charts/yilu-common/README.md > docs/README.md
          git add docs/README.md
          git commit -m "Copied README.md from main branch to docs in yilu-common"
          git push origin yilu-common
